# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Project setup
    - name: Project setup
      run: pod install

    # Static code analysis
    - name: Analyze
      run: xcodebuild -workspace APBMealPlanner.xcworkspace -scheme APBMealPlanner -sdk iphonesimulator13.2 clean analyze
      
    # Builds the application
    - name: Build and test
      run: xcodebuild clean test -workspace APBMealPlanner.xcworkspace -scheme APBMealPlanner CODE_SIGN_IDENTITY="" -destination 'platform=iOS Simulator,OS=13.3,name=iPhone 11 Pro' CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
